[package]
name = "kafkaesque"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
comrak = "0.18.0"
json = "0.12.4"
time = { version = "0.3.21", features = ["parsing"] }
