[package]
name = "KohonenGrossberg-NN"
version = "0.1.0"
authors = ["Juxhin Dyrmishi Brigjaj <juxhinbox@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
rand = "^0.5.5"
clap = {version = "2.32", features = ["yaml"]}